[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "samsung-mx-t40"
version = "0.0.1"
description = "A library for communication with Samsung MX-T40 devices"
readme = "README.md"
requires-python = ">=3.10,<3.11"
license = "GPL-3.0-only"
authors = [
  { name = "Fabien Carrion", email = "fabien@carrion.mx" },
]
classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
]
dependencies = [
  "pybluez2==0.46",
]

[tool.setuptools]
packages = ["samsungmxt40"]

[tool.uv]
override-dependencies = [
  "pyobjc-core; sys_platform == 'darwin'",
  "pyobjc-framework-cocoa; sys_platform == 'darwin'",
  "pyobjc-framework-libdispatch; sys_platform == 'darwin'",
]
